name: Build and test

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Pull Carbon Intensity Stub
        uses: actions/@v2
        with:
          repository: https://github.com/mycp98/Energy-Source-Checker-Stubs

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn clean install


