name: Build and test

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Carbon Intensity Stub
        uses: actions/checkout@v2
        with:
          repository: mycp98/Energy-Source-Checker-Stubs

      - name: Build and Run stub
        run: docker build -t stubs . && docker run -d -p 8081:8080 stubs &


      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn clean install

      - name: Run Integration Tests
        run: mvn failsafe:integration-test



